[package]
name = "parquet_viewer"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
radui = { workspace = true }
uuid = { workspace = true }
quick-xml = {version = "0.31.0", features = ["serialize"]}
