[package]
name = "radui"
version = "0.1.0"
edition = "2021"

[dependencies]
glutin = "0.30.0"
glutin-winit = "0.3.0"
winit = "0.28.1"
raw-window-handle = "0.5.0"
femtovg = "0.9.1"
yaserde = "0.7.1"
yaserde_derive = "0.7.1"
xsd-types = {git = "https://github.com/avantgardnerio/xsd-parser-rs.git", rev = "b70a36b166947201a0073c9528815c39e3c72789"}
xsd-parser = {git = "https://github.com/avantgardnerio/xsd-parser-rs.git", rev = "b70a36b166947201a0073c9528815c39e3c72789"}
xsd-macro-utils = {git = "https://github.com/avantgardnerio/xsd-parser-rs.git", rev = "b70a36b166947201a0073c9528815c39e3c72789"}
xml-rs = "0.8"
itertools = "0.12.1"
resource = "0.5.0"

[build-dependencies]
xsd-parser = {git = "https://github.com/avantgardnerio/xsd-parser-rs.git", rev = "b70a36b166947201a0073c9528815c39e3c72789"}
